/*
 * Authors
 * Name: Sirinian Aram Emmanouil
 */


package testRunner;

import org.junit.runner.JUnitCore;
import org.junit.runner.Result;
import org.junit.runner.RunWith;
import org.junit.runner.notification.Failure;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import testUS1.GivenArticleTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate;
import testUS1.GivenBlankTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate;
import testUS1.GivenBookTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate;
import testUS1.GivenLetterTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate;
import testUS1.GivenReportTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate;
import testUS2.GivenAnyDocumentWhenEditingDocumentContentsThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents;
import testUS3.GivenArticleDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents;
import testUS3.GivenBookDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents;
import testUS3.GivenLetterDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents;
import testUS3.GivenReportDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents;
import testUS4.GivenStableStrategyIsEnabledWhenRollbackToPreviouseVersionsThenDocumentContentsChangeRight;
import testUS4.GivenVolatileStrategyIsEnabledWhenRollbackToPreviouseVersionsThenDocumentContentsChangeRight;
import testUS5.GivenStableStrategyInVersionsManagerWhenSetVolatileStrategyThenStrategyInVersionsManagerChangeRight;
import testUS5.GivenVolatileStrategyInVersionsManagerWhenSetStableStrategyThenStrategyInVersionsManagerChangeRight;
import testUS6.GivenVersionsManagerWhenDisableVersionsManagerThenVersionsHistoryRemainsUnchanged;
import testUS7.GivenBunchOfVersionsWhenRollbackToPreviousVersionThenDocumentContentsChangeRight;
import testUS8.GivenContentsOfAnyDocumentWhenSaveDocumentThenContentsInDocumentAndInFileAreTheSame;
import testUS9.GivenContentsOfAnyDocumentWhenLoadDocumentThenContentsInDocumentAndInFileAreTheSame;

@RunWith(Suite.class)
@SuiteClasses({ GivenArticleTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
		GivenBookTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
		GivenLetterTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
		GivenReportTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
		GivenBlankTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
		GivenAnyDocumentWhenEditingDocumentContentsThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
		GivenArticleDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
		GivenBookDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
		GivenLetterDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
		GivenReportDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
		GivenStableStrategyIsEnabledWhenRollbackToPreviouseVersionsThenDocumentContentsChangeRight.class,
		GivenVolatileStrategyIsEnabledWhenRollbackToPreviouseVersionsThenDocumentContentsChangeRight.class,
		GivenStableStrategyInVersionsManagerWhenSetVolatileStrategyThenStrategyInVersionsManagerChangeRight.class,
		GivenVolatileStrategyInVersionsManagerWhenSetStableStrategyThenStrategyInVersionsManagerChangeRight.class,
		GivenVersionsManagerWhenDisableVersionsManagerThenVersionsHistoryRemainsUnchanged.class,
		GivenBunchOfVersionsWhenRollbackToPreviousVersionThenDocumentContentsChangeRight.class,
		GivenContentsOfAnyDocumentWhenSaveDocumentThenContentsInDocumentAndInFileAreTheSame.class,
		GivenContentsOfAnyDocumentWhenLoadDocumentThenContentsInDocumentAndInFileAreTheSame.class})
public class TestRunner {
	public static void main(String[] args) {
		Result result = JUnitCore.runClasses(
				GivenArticleTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
				GivenBookTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
				GivenLetterTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
				GivenReportTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
				GivenBlankTypeWhenCreatingNewDocumentThenDocumentContentsContainTheRightTemplate.class,
				GivenAnyDocumentWhenEditingDocumentContentsThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
				GivenArticleDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
				GivenBookDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
				GivenLetterDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddChapterThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddEnumerationListEnumerateThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddEnumerationListItemizeThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddFigureThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddSectionThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddSubsectionThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddSubsubsectionThenDocumentContainTheRightContents.class,
				GivenReportDocumentWhenAddingLatexCommandAddTableThenDocumentContainTheRightContents.class,
				GivenStableStrategyIsEnabledWhenRollbackToPreviouseVersionsThenDocumentContentsChangeRight.class,
				GivenVolatileStrategyIsEnabledWhenRollbackToPreviouseVersionsThenDocumentContentsChangeRight.class,
				GivenStableStrategyInVersionsManagerWhenSetVolatileStrategyThenStrategyInVersionsManagerChangeRight.class,
				GivenVolatileStrategyInVersionsManagerWhenSetStableStrategyThenStrategyInVersionsManagerChangeRight.class,
				GivenVersionsManagerWhenDisableVersionsManagerThenVersionsHistoryRemainsUnchanged.class,
				GivenBunchOfVersionsWhenRollbackToPreviousVersionThenDocumentContentsChangeRight.class,
				GivenContentsOfAnyDocumentWhenSaveDocumentThenContentsInDocumentAndInFileAreTheSame.class,
				GivenContentsOfAnyDocumentWhenLoadDocumentThenContentsInDocumentAndInFileAreTheSame.class);

		for(Failure failure : result.getFailures()) {
			System.out.println(failure.toString());
		}

		System.out.println(result.wasSuccessful());
	}
}
